CREATE DATABASE IF NOT EXISTS crs
CHARACTER SET cp1251
COLLATE cp1251_general_ci;

USE crs;
CREATE TABLE IF NOT EXISTS dat_vars(
  ID_VAR INT(11) NOT NULL AUTO_INCREMENT,
  S_SYS_NAME VARCHAR(32) NOT NULL,
  S_TYPE VARCHAR(128) NOT NULL,
  S_VALUE VARCHAR(255) NOT NULL,
  S_NAME VARCHAR(255) DEFAULT NULL,
  S_DESC VARCHAR(4000) DEFAULT NULL,
  D_CREATE DATE DEFAULT NULL,
  D_EDIT DATE DEFAULT NULL,
  PRIMARY KEY (ID_VAR),
  UNIQUE INDEX S_SYS_NAME (S_SYS_NAME)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET cp1251
COLLATE cp1251_general_ci;